version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432"
    env_file:
      - config/.env.db
    volumes:
    - pgdata:/var/lib/postgresql/data/
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - postgres
    volumes:
      - .:/app
    env_file:
      - config/.env.app
    depends_on:
      - postgres

volumes:
  pgdata: